if (${ENABLE_EIGEN})
    message(STATUS "Eigen3 is enabled")
    add_compile_definitions("GF_EIGEN3")
    find_package(Eigen3 REQUIRED)
    if (${CMAKE_HOST_UNIX})
        set(Eigen3_INCLUDE_DIR "/usr/include/eigen3")
    endif ()
    include_directories(${Eigen3_INCLUDE_DIR})
    if (${Eigen3_FOUND})
        message(STATUS "Found eigen3 (found version: ${Eigen3_VERSION})")
    endif ()
else ()
    remove_definitions("GF_EIGEN3")
endif ()