
#ifndef SLAMRECONSTRUCTION_IMUPREINTEGRATION_H
#define SLAMRECONSTRUCTION_IMUPREINTEGRATION_H

namespace gf{
    class IMUPreIntegration {

    };
}



#endif //SLAMRECONSTRUCTION_IMUPREINTEGRATION_H
